### ISSUE TITLE
Code-formatted text is white on a white background, making it hard to see

### ISSUE THREAD

**Issue by aSemy** [llvm/llvm-blog-www#52]
Most of the code snippets in this blog are rendered as white on a light background, meaning they are difficult to see.

https://blog.llvm.org/2019/11/deterministic-builds-with-clang-and-lld.html

<img width="738" alt="image" src="https://github.com/user-attachments/assets/79580e39-6bec-4755-a152-482adcf1709a">

**Comment by DavidSpickett** [comment]
I didn't see this with Chrome but did with Firefox (perhaps there is some dark mode setting difference).

This article is actually in the repo as an HTML file, it seems that all articles before some point in 2020 are. After that they are Markdown and use a theme (https://github.com/avianto/hugo-kiera).

Articles that use the theme are ok, the HTML ones are not because they hard code the background colour for this.

Thanks for bringing this to our attention. I'm not sure we will be able to fix it though. I wonder if converting the HTML files to back to Markdown would be possible.

**Comment by aSemy** [comment]
Hi, thanks for looking into it. I am using Chrome (with darkmode enabled), so I wonder why you saw a difference.
